### ISSUE TITLE
[feat] cicd 적용

### ISSUE THREAD

**Issue by OJOJIN** [Domitory-CheckMate/BackEnd#3]
## 📢  Feature Issue
cicd 입니다

## 📝  To-do
- [x] DockerFIle 생성
- [x] git action workflow 생성
- [x] ec2생성
- [x] ec2 도메인 등록
- [x] nginx 설정

**Comment by ziiyouth** [comment]
화이팅팅탱

**Comment by RyuKwanKon** [comment]
팅팅탱탱
